name: Terraform Plan and Apply with Approval

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
      pipeline_action:
        description: 'Pipeline action (create or destroy)'
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tag
        env:
          TF_WORKSPACE: ${{ inputs.environment }}
          REPOSITORY_NAME: ${{ github.repository }}
        run: |
          EPOCH=$(($(date +%s%N)/1000000)) \
      
          curl -X POST "https://a2ops.grafana.net/api/annotations" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.GRAFANA_ANNOTATIONS_KEY }}" \
            -d '{
              "created": '"$EPOCH"',
              "updated": '"$EPOCH"',
              "time": '"$EPOCH"',
              "timeEnd": '"$EPOCH"',
              "text": "Deployment",
              "tags": [
                "deployment"
                "kind:${{ inputs.pipeline_action }}",
                "env:${{ inputs.environment }}"
              ]
            }'
