on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'DEV'
        type: choice 
        options:
          - DEV
          - QA
      pipeline_action:
        description: 'pipeline action'
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - destroy


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display variables
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "App Version: ${{ inputs.pipeline_action }}"

      - name: Deploy application
        run: echo "Deploying version ${{ inputs.environment }} to ${{ inputs.environment == 'production' && 'production' || 'staging' }}..." && [ "${{ inputs.environment }}" = "production" ] && echo "Run production commands here" || echo "Run staging commands here"
